# Generated by Django 3.1.6 on 2021-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('guid', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=320)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
